name: dotnet package
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x', '9.0.x' ]
        configuration: [ 'Debug', 'Release' ]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Display .NET version
        run: dotnet --version
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore --configuration ${{ matrix.configuration }}
      
      - name: Test
        run: dotnet test --no-build --configuration ${{ matrix.configuration }} --verbosity normal
      
      - name: Publish
        run: dotnet publish --no-build --configuration ${{ matrix.configuration }} --output ./build-output/${{ matrix.configuration }}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.configuration }}-dotnet-${{ matrix.dotnet-version }}
          path: ./build-output/${{ matrix.configuration }}/**
